@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for Flight Management System

Container(spa, "Single Page Application", "typescript and angular", "Provides all the functionality to customers for searching and booking flights")
Container(db, "Database", "Relational database schema", "Stores data for the application")

Container_Boundary(flight, "Flight Container") {
  Component(flightController, "Flight Controller", "Rest Controller", "Handles REST requests for flights")
  Component(flightService, "Flight Service", "Service", "Implements the business logic, algorithms and rules related to flights.")
  Component(flightRepository, "Flight Repository", "Repository", "Performs data storage and retrieval operations")
  Rel(flightController, flightService, "Uses")
  Rel(flightService, flightRepository, "Uses")
}
Container_Boundary(user, "User Container") {
  Component(userController, "User Controller", "Rest Controller", "Handles REST requests for users.")
  Component(userService, "User Service", "Service", "Implements the business logic, algorithms and rules related to users.")
  Component(userRepository, "User Repository", "Repository", "Performs data storage and retrieval operations")
  Rel(userController, userService, "Uses")
  Rel(userService, userRepository, "Uses")
}

Rel(spa, flightController, "Uses", "JSON/HTTPS")
Rel(spa, userController, "Uses", "JSON/HTTPS")

Rel(flightRepository, db, "Uses", "JDBC")
Rel(userRepository, db, "Uses", "JDBC")

@enduml
