@startuml

skinparam linetype ortho
skinparam nodesep 100

entity "flights" as e01 {
  id : number <<generated>>
  --
  airline_id : number
  origin_airport_id : number
  destination_airport_id : number
  flight_number : varchar(20)
  departure_time : timestamp
  arrival_time : timestamp
  capacity : number
  available_seats : number
}

entity "airline" as e02 {
  id : number <<generated>>
  --
  name : varchar(100)
  code : varchar(10)
}

entity "airport" as e03 {
  id : number <<generated>>
  --
  name : varchar(100)
  code : varchar(10)
  address_1 : varchar(40)
  address_2 : varchar(40)
  city : varchar(30)
  state : varchar(30)
  postal_code : varchar(10)
  country : varchar(30)
}

entity "customer" as e04 {
  id : number <<generated>>
  --
  first_name : varchar(40)
  last_name : varchar(40)
  address_1 : varchar(100)
  address_2 : varchar(100)
  city : varchar(30)
  postal_code : varchar(10)
  country : varchar(40)
}

e01 }o.up.|| e02
e01 }o.up.|| e03

@enduml

