@startuml

skinparam linetype ortho
skinparam nodesep 100

entity "flights" as e01 {
  id : number <<generated>>
  --
  airline_id : number
  origin_airport_id : number
  destination_airport_id : number
  flight_number : varchar(20)
  departure_time : timestamp
  arrival_time : timestamp
  capacity : number
  available_seats : number
}

entity "airlines" as e02 {
  id : number <<generated>>
  --
  name : varchar(100)
  code : varchar(10)
}

entity "airports" as e03 {
  id : number <<generated>>
  --
  name : varchar(100)
  code : varchar(10)
}

entity "passengers" as e04 {
  id : number <<generated>>
  --
  first_name : varchar(40)
  last_name : varchar(40)
  email : varchar(100)
  phone : varchar(15)
}

entity "bookings" as e05 {
  id : number <<generated>>
  --
  flight_id : number
  passenger_id : number
  seat_number varchar(3)
}

entity "airports_flights" as e06 {
  airport_id : number
  flight_id : number
}

entity "airlines_flights" as e07 {
  airport_id : number
  flight_id : number
}

e03 ||.right.o{ e06
e06 }o.right.|| e01
e02 ||.up.o{ e07
e07 }o.up.|| e01
e01 ||.right.|{ e05
e05 }|.right.|| e04


@enduml

